project:
  type: website
  resources:
    - "assets/australia.geojson"
    - "locations.json"

website:
  title: "Is it hot right now?"
  search: false
  navbar:
    background: "#ffffff"
format:
  html:
    theme:
      - default
      - style.scss



