project:
  type: website

website:
  title: "Is it hot right now?"
  search: false
  navbar:
    background: "#ffffff"

    # left:
    #   # - href: index.qmd
    #   #   text: Home
    #   # - about.qmd

format:
  html:
    theme:
      - default
      - style.scss



